

name: anuan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  cron:

    runs-on: ubuntu-latest
    timeout-minutes: 1

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - uses: actions/checkout@v3
    - name: ping si gitpod
      run: ping -c 2 6000-gitjomb-musicv2-78y9u7etyee.ws-us84.gitpod.io

