

name: anuan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  cron:

    runs-on: windows-latest
    timeout-minutes: 1

    steps:
    - name: ngeping
      run: ping 6000-gitjomb-musicv2-78y9u7etyee.ws-us84.gitpod.io

